(() => {
  'use strict';
  const config=window.RRN_SUPABASE;
  if(!config?.url||!config?.anonKey||!window.supabase?.createClient){console.error('Supabase indisponível.');return;}
  const client=window.supabase.createClient(config.url,config.anonKey,{auth:{persistSession:true,autoRefreshToken:true}});
  const $=id=>document.getElementById(id);
  const state={user:null,profile:null,tenant:null,team:new Map(),customers:new Map(),tickets:[],filter:'all',selected:null,ticketChannel:null,messageChannel:null};
  const statusLabels={new:'Novo',assigned:'Atribuído',in_progress:'Em atendimento',waiting_requester:'Aguardando usuário',resolved:'Resolvido',closed:'Encerrado',reopened:'Reaberto'};
  const priorityLabels={low:'Baixa',medium:'Média',high:'Alta',critical:'Crítica'};
  const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const formatDate=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
  function formatDuration(ms){if(!Number.isFinite(ms))return'—';const neg=ms<0,total=Math.floor(Math.abs(ms)/1000),d=Math.floor(total/86400),h=Math.floor(total%86400/3600),m=Math.floor(total%3600/60),s=total%60;const value=d?`${d}d ${h}h`:h?`${h}h ${m}m`:`${m}m ${s}s`;return neg?`${value} em atraso`:value;}
  function slaDue(ticket,type){const first=type==='first';if(first&&ticket.first_response_at)return{done:true,text:`Respondido em ${formatDate(ticket.first_response_at)}`};if(!first&&['resolved','closed'].includes(ticket.status))return{done:true,text:ticket.resolved_at?`Resolvido em ${formatDate(ticket.resolved_at)}`:'Resolvido'};const due=new Date(first?ticket.first_response_due_at:ticket.resolution_due_at).getTime();if(!Number.isFinite(due))return{done:false,text:'—'};const diff=due-Date.now();return{done:false,overdue:diff<0,text:diff<0?`${formatDuration(diff)} em atraso`.replace(' em atraso em atraso',' em atraso'):`${formatDuration(diff)} restantes`};}
  function handlingTime(ticket){if(!ticket.handling_started_at)return'Não iniciado';const end=ticket.resolved_at||ticket.closed_at||new Date().toISOString();return formatDuration(new Date(end)-new Date(ticket.handling_started_at));}
  function toast(message,type=''){const el=$('deskToast');el.textContent=message;el.className=`desk-toast ${type}`.trim();el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,3200);}
  function canOperate(){return ['admin','operador'].includes(state.profile?.role);}
  async function bootSession(){const{data:{session}}=await client.auth.getSession();if(!session?.user){location.href='/login.html';return false;}state.user=session.user;const{data:profile,error}=await client.from('profiles').select('user_id,tenant_id,name,email,role,status').eq('user_id',session.user.id).maybeSingle();if(error||!profile||profile.status!=='active'){location.href='/login.html';return false;}state.profile=profile;const[{data:tenant},{data:team}]=await Promise.all([client.from('tenants').select('id,name,slug').eq('id',profile.tenant_id).maybeSingle(),client.from('profiles').select('user_id,name,email,role,status').eq('tenant_id',profile.tenant_id).eq('status','active')]);state.tenant=tenant||{id:profile.tenant_id,name:'Workspace'};(team||[]).forEach(member=>state.team.set(member.user_id,member));$('deskWorkspaceLabel').textContent=`${state.tenant.name} · ${profile.name} · ${profile.role}`;if(!canOperate())$('deskActionRow').hidden=true;return true;}
  async function loadTickets(keep=true){const{data,error}=await client.from('support_tickets').select('*').eq('tenant_id',state.profile.tenant_id).order('opened_at',{ascending:false});if(error){toast(error.message||'Falha ao carregar chamados.','error');return;}state.tickets=data||[];const ids=[...new Set(state.tickets.map(t=>t.requester_id).filter(Boolean))];state.customers.clear();if(ids.length){const{data:customers}=await client.from('support_customers').select('id,name,email,phone,employee_number').in('id',ids);(customers||[]).forEach(c=>state.customers.set(c.id,c));}renderKpis();renderList();if(keep&&state.selected){const fresh=state.tickets.find(t=>t.id===state.selected.id);if(fresh){state.selected=fresh;renderDetail();}}}
  function renderKpis(){const today=new Date();today.setHours(0,0,0,0);$('deskKpiNew').textContent=state.tickets.filter(t=>['new','reopened'].includes(t.status)).length;$('deskKpiProgress').textContent=state.tickets.filter(t=>['assigned','in_progress'].includes(t.status)).length;$('deskKpiWaiting').textContent=state.tickets.filter(t=>t.status==='waiting_requester').length;$('deskKpiResolved').textContent=state.tickets.filter(t=>t.resolved_at&&new Date(t.resolved_at)>=today).length;}
  function isSlaNear(ticket){if(['resolved','closed'].includes(ticket.status))return false;const due=!ticket.first_response_at?ticket.first_response_due_at:ticket.resolution_due_at;if(!due)return false;return new Date(due)-Date.now()<=60*60*1000;}
  function filteredTickets(){return state.tickets.filter(t=>state.filter==='all'?true:state.filter==='new'?['new','reopened'].includes(t.status):state.filter==='mine'?t.assigned_to===state.user.id:state.filter==='sla'?isSlaNear(t):state.filter==='critical'?t.priority==='critical':true);}
  function renderList(){const tickets=filteredTickets(),box=$('deskTicketList');$('deskListCount').textContent=`${tickets.length} ${tickets.length===1?'chamado':'chamados'}`;if(!tickets.length){box.innerHTML='<div class="desk-info-card"><strong>Nenhum chamado neste filtro.</strong><small>A fila será atualizada automaticamente.</small></div>';return;}box.innerHTML=tickets.map(t=>{const requester=state.customers.get(t.requester_id);const first=slaDue(t,'first'),resolution=slaDue(t,'resolution'),active=!t.first_response_at?first:resolution;const asset=t.asset_display||t.asset_tag_snapshot||t.machine_query||'Sem ativo vinculado';return `<button type="button" class="desk-ticket-card ${state.selected?.id===t.id?'active':''}" data-ticket-id="${t.id}"><div class="desk-ticket-top"><strong>#${t.ticket_number}</strong><span class="desk-badge ${t.status}">${statusLabels[t.status]||t.status}</span></div><h3>${escapeHtml(t.title)}</h3><p>${escapeHtml(requester?.name||'Solicitante')} · ${escapeHtml(t.sector_name_snapshot||asset)}</p><div class="desk-ticket-footer"><span class="desk-priority ${t.priority}">${priorityLabels[t.priority]||t.priority}</span><span class="desk-sla-text ${active.overdue?'overdue':''}">${escapeHtml(active.text)}</span></div></button>`}).join('');}
  async function selectTicket(id){const ticket=state.tickets.find(t=>t.id===id);if(!ticket)return;state.selected=ticket;renderList();renderDetail();await loadMessages(id);subscribeMessages(id);}
  function renderDetail(){const t=state.selected;if(!t)return;$('deskEmpty').hidden=true;$('deskTicketView').hidden=false;const requester=state.customers.get(t.requester_id);$('deskTicketNumber').textContent=`Chamado #${t.ticket_number} · aberto em ${formatDate(t.opened_at)}`;$('deskTicketTitle').textContent=t.title;$('deskTicketStatus').textContent=statusLabels[t.status]||t.status;$('deskTicketStatus').className=`desk-badge ${t.status}`;$('deskTicketPriority').textContent=priorityLabels[t.priority]||t.priority;$('deskTicketPriority').className=`desk-priority ${t.priority}`;$('deskRequesterName').textContent=requester?.name||'Solicitante';$('deskRequesterMeta').textContent=[requester?.employee_number?`Matrícula ${requester.employee_number}`:null,requester?.email,requester?.phone].filter(Boolean).join(' · ')||'Sem dados adicionais';$('deskAssetName').textContent=t.asset_display||t.machine_query||'Equipamento não vinculado';$('deskAssetMeta').textContent=[t.asset_tag_snapshot?`PAT: ${t.asset_tag_snapshot}`:null,t.asset_serial_snapshot?`SN: ${t.asset_serial_snapshot}`:null,t.asset_hostname_snapshot?`Host: ${t.asset_hostname_snapshot}`:null,t.sector_name_snapshot?`Setor: ${t.sector_name_snapshot}`:null].filter(Boolean).join(' · ')||'O ativo pode ser vinculado posteriormente';const first=slaDue(t,'first'),resolution=slaDue(t,'resolution');$('deskFirstResponseSla').textContent=first.text;$('deskResolutionSla').textContent=resolution.text;$('deskHandlingTime').textContent=handlingTime(t);const closed=['resolved','closed'].includes(t.status);const claim=$('deskClaimBtn'),waiting=$('deskWaitingBtn'),resolve=$('deskResolveBtn');claim.hidden=!canOperate()||closed||(t.assigned_to===state.user.id&&['assigned','in_progress'].includes(t.status));claim.textContent=t.assigned_to&&t.assigned_to!==state.user.id?`Assumir de ${state.team.get(t.assigned_to)?.name||'outro técnico'}`:'Assumir chamado';waiting.hidden=!canOperate()||closed;resolve.hidden=!canOperate()||closed;const input=$('deskMessageInput'),send=$('deskMessageForm').querySelector('button');input.disabled=t.status==='closed';send.disabled=t.status==='closed';}
  async function loadMessages(ticketId){const{data,error}=await client.from('support_ticket_messages').select('id,ticket_id,sender_id,sender_type,message,created_at').eq('ticket_id',ticketId).order('created_at',{ascending:true});if(error){toast(error.message||'Falha ao carregar conversa.','error');return;}const box=$('deskMessages');if(!data?.length){box.innerHTML='<div class="desk-info-card"><strong>Sem mensagens ainda.</strong><small>Responda para registrar o primeiro atendimento.</small></div>';return;}box.innerHTML=data.map(m=>{const support=m.sender_type==='support';const name=support?(state.team.get(m.sender_id)?.name||'Suporte'):(state.customers.get(state.selected?.requester_id)?.name||'Solicitante');return `<article class="desk-message ${support?'support':''}"><strong>${escapeHtml(name)}</strong><p>${escapeHtml(m.message)}</p><small>${formatDate(m.created_at)}</small></article>`}).join('');box.scrollTop=box.scrollHeight;}
  async function sendMessage(event){event.preventDefault();if(!state.selected||!canOperate())return;const input=$('deskMessageInput'),message=input.value.trim();if(!message)return;input.value='';const{error}=await client.from('support_ticket_messages').insert({ticket_id:state.selected.id,message});if(error){input.value=message;toast(error.message||'Falha ao enviar mensagem.','error');return;}await Promise.all([loadMessages(state.selected.id),loadTickets()]);}
  async function updateTicket(patch,success){if(!state.selected||!canOperate())return;const{data,error}=await client.from('support_tickets').update(patch).eq('id',state.selected.id).select('*').single();if(error){toast(error.message||'Não foi possível atualizar o chamado.','error');return;}state.selected=data;toast(success,'success');await loadTickets();renderDetail();}
  async function claim(){const now=new Date().toISOString();await updateTicket({assigned_to:state.user.id,status:'in_progress',first_response_at:state.selected.first_response_at||now,handling_started_at:state.selected.handling_started_at||now},'Chamado assumido.');}
  async function waiting(){await updateTicket({status:'waiting_requester'},'Chamado marcado como aguardando usuário.');}
  function openResolve(){if(!state.selected||!canOperate())return;$('deskResolutionInput').value=state.selected.resolution||'';$('deskCauseInput').value=state.selected.cause||'';$('deskResolveModal').hidden=false;setTimeout(()=>$('deskResolutionInput').focus(),0);}
  function closeResolve(){$('deskResolveModal').hidden=true;}
  async function resolveTicket(event){event.preventDefault();const resolution=$('deskResolutionInput').value.trim(),cause=$('deskCauseInput').value.trim();if(!resolution)return;const now=new Date().toISOString();closeResolve();await updateTicket({assigned_to:state.selected.assigned_to||state.user.id,status:'resolved',first_response_at:state.selected.first_response_at||now,handling_started_at:state.selected.handling_started_at||now,resolved_at:now,resolution,cause:cause||null},'Chamado resolvido e enviado para confirmação do usuário.');}
  function subscribeTickets(){if(state.ticketChannel)client.removeChannel(state.ticketChannel);state.ticketChannel=client.channel(`desk-${state.profile.tenant_id}`).on('postgres_changes',{event:'*',schema:'public',table:'support_tickets',filter:`tenant_id=eq.${state.profile.tenant_id}`},()=>loadTickets()).subscribe();}
  function subscribeMessages(ticketId){if(state.messageChannel)client.removeChannel(state.messageChannel);state.messageChannel=client.channel(`desk-msg-${ticketId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'support_ticket_messages',filter:`ticket_id=eq.${ticketId}`},()=>state.selected?.id===ticketId&&loadMessages(ticketId)).subscribe();}
  function bind(){document.querySelectorAll('[data-desk-filter]').forEach(btn=>btn.addEventListener('click',()=>{state.filter=btn.dataset.deskFilter;document.querySelectorAll('[data-desk-filter]').forEach(b=>b.classList.toggle('active',b===btn));renderList();}));$('deskTicketList').addEventListener('click',e=>{const card=e.target.closest('[data-ticket-id]');if(card)selectTicket(card.dataset.ticketId);});$('deskRefreshBtn').addEventListener('click',()=>loadTickets());$('deskMessageForm').addEventListener('submit',sendMessage);$('deskClaimBtn').addEventListener('click',claim);$('deskWaitingBtn').addEventListener('click',waiting);$('deskResolveBtn').addEventListener('click',openResolve);$('deskResolveCancel').addEventListener('click',closeResolve);$('deskResolveForm').addEventListener('submit',resolveTicket);$('deskResolveModal').addEventListener('click',e=>{if(e.target===$('deskResolveModal'))closeResolve();});window.addEventListener('keydown',e=>{if(e.key==='Escape')closeResolve();});}
  async function boot(){bind();if(!await bootSession())return;await loadTickets();subscribeTickets();setInterval(()=>{renderKpis();renderList();if(state.selected)renderDetail();},1000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
