(() => {
'use strict';
const cfg=window.RRN_SUPABASE||{};const notice=document.getElementById('pageNotice');
const client=window.supabase?.createClient?.(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let me=null,isPlatformAdmin=false,tenants=[],selectedTenantId=null,members=[],invites=[],branding=null;
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){const e=$('toast');e.textContent=t;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,2600)}
function showNotice(t){notice.hidden=false;notice.textContent=t}function roleLabel(r){return{admin:'Administrador',operador:'Operador',monitoramento:'Monitoramento'}[r]||r}
function dateLabel(v){return v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(v)):'—'}
function currentTenant(){return tenants.find(t=>t.id===selectedTenantId)||null}
function switchView(name){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelectorAll('[data-view-panel]').forEach(p=>p.classList.toggle('active',p.dataset.viewPanel===name))}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
async function getMe(uid){const {data,error}=await client.from('profiles').select('user_id,tenant_id,name,email,role,status,tenants(name,slug)').eq('user_id',uid).single();if(error)throw error;return data}
async function checkPlatform(){const {data,error}=await client.rpc('is_platform_admin');if(error)throw error;return !!data}
async function loadTenants(){let q=client.from('tenants').select('id,name,slug,status,created_at');if(!isPlatformAdmin)q=q.eq('id',me.tenant_id);const {data,error}=await q.order('created_at');if(error)throw error;tenants=data||[];if(!selectedTenantId||!tenants.some(t=>t.id===selectedTenantId))selectedTenantId=isPlatformAdmin?(tenants[0]?.id||me.tenant_id):me.tenant_id;renderTenantContext();await loadTenantData()}
function renderTenantContext(){const t=currentTenant();$('tenantName').textContent=t?.name||'—';$('tenantSlug').textContent=t?.slug||'—';$('companyName').value=t?.name||'';$('companySlug').value=t?.slug||'';$('companyStatus').value=t?.status||'active';const s=$('tenantSelector');s.innerHTML=tenants.map(x=>`<option value="${x.id}" ${x.id===selectedTenantId?'selected':''}>${esc(x.name)}</option>`).join('');$('companiesNav').hidden=!isPlatformAdmin;$('kpiCompanies').textContent=isPlatformAdmin?tenants.length:'1';$('kpiActiveCompanies').textContent=tenants.filter(x=>x.status==='active').length}
$('tenantSelector').addEventListener('change',async e=>{selectedTenantId=e.target.value;renderTenantContext();await loadTenantData()});
async function loadTenantData(){await Promise.all([loadMembers(),loadInvites(),loadBranding()]);renderCompanies();updateKpis()}
async function loadMembers(){const {data,error}=await client.from('profiles').select('user_id,name,email,role,status,created_at').eq('tenant_id',selectedTenantId).order('created_at');if(error)throw error;members=data||[];$('memberCount').textContent=`${members.length} ${members.length===1?'usuário':'usuários'}`;$('membersBody').innerHTML=members.length?members.map(u=>{const self=u.user_id===me.user_id;return `<tr><td class="user-cell"><strong>${esc(u.name||'Sem nome')}</strong><small>${esc(u.email||'')}${self?' · você':''}</small></td><td><span class="badge badge-${esc(u.role)}">${esc(roleLabel(u.role))}</span></td><td><span class="badge badge-${esc(u.status)}">${u.status==='active'?'Ativo':'Inativo'}</span></td><td>${dateLabel(u.created_at)}</td><td class="align-right"><div class="actions"><button class="action-btn" data-role-id="${u.user_id}" data-role="${u.role}" ${self?'disabled':''}>Perfil</button><button class="action-btn ${u.status==='active'?'danger':''}" data-status-id="${u.user_id}" data-status="${u.status}" ${self?'disabled':''}>${u.status==='active'?'Desativar':'Ativar'}</button></div></td></tr>`}).join(''):'<tr><td colspan="5">Nenhum usuário.</td></tr>';bindUserActions()}
function bindUserActions(){document.querySelectorAll('[data-role-id]').forEach(b=>b.onclick=async()=>{const next=prompt('Novo perfil: admin, operador ou monitoramento',b.dataset.role);if(!next)return;const r=next.trim().toLowerCase();if(!['admin','operador','monitoramento'].includes(r))return toast('Perfil inválido.');const {error}=await client.from('profiles').update({role:r}).eq('user_id',b.dataset.roleId).eq('tenant_id',selectedTenantId);if(error)return toast(error.message);toast('Perfil atualizado.');await loadMembers()});document.querySelectorAll('[data-status-id]').forEach(b=>b.onclick=async()=>{const next=b.dataset.status==='active'?'inactive':'active';const {error}=await client.from('profiles').update({status:next}).eq('user_id',b.dataset.statusId).eq('tenant_id',selectedTenantId);if(error)return toast(error.message);toast('Status atualizado.');await loadMembers()})}
async function loadInvites(){const {data,error}=await client.from('tenant_invitations').select('id,email,role,expires_at,used_at,created_at').eq('tenant_id',selectedTenantId).order('created_at',{ascending:false}).limit(50);if(error)throw error;invites=data||[];$('invitesBody').innerHTML=invites.length?invites.map(i=>{const expired=!i.used_at&&new Date(i.expires_at)<new Date();const st=i.used_at?'used':expired?'expired':'pending';const label=st==='used'?'Utilizado':st==='expired'?'Expirado':'Pendente';return `<tr><td>${esc(i.email||'Qualquer e-mail')}</td><td>${esc(roleLabel(i.role))}</td><td>${dateLabel(i.expires_at)}</td><td><span class="badge badge-${st}">${label}</span></td><td class="align-right">${st==='pending'?`<button class="action-btn danger" data-delete-invite="${i.id}">Revogar</button>`:''}</td></tr>`}).join(''):'<tr><td colspan="5">Nenhum convite.</td></tr>';document.querySelectorAll('[data-delete-invite]').forEach(b=>b.onclick=async()=>{const {error}=await client.from('tenant_invitations').delete().eq('id',b.dataset.deleteInvite);if(error)return toast(error.message);toast('Convite revogado.');await loadInvites()})}
function makeCode(){const a=new Uint8Array(24);crypto.getRandomValues(a);return Array.from(a,x=>x.toString(16).padStart(2,'0')).join('')}async function hash(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(d),x=>x.toString(16).padStart(2,'0')).join('')}
$('inviteForm').addEventListener('submit',async e=>{e.preventDefault();const code=makeCode();const payload={tenant_id:selectedTenantId,email:$('inviteEmail').value.trim().toLowerCase(),token_hash:await hash(code),role:$('inviteRole').value,expires_at:new Date(Date.now()+Number($('inviteDays').value)*86400000).toISOString(),created_by:me.user_id};const {error}=await client.from('tenant_invitations').insert(payload);if(error)return toast(error.message);$('inviteCode').textContent=code;$('inviteResult').hidden=false;e.target.reset();toast('Convite criado.');await loadInvites()});$('copyInviteButton').onclick=async()=>{await navigator.clipboard.writeText($('inviteCode').textContent||'');toast('Código copiado.')};$('refreshButton').onclick=loadTenantData;
async function loadBranding(){const {data,error}=await client.from('tenant_branding').select('*').eq('tenant_id',selectedTenantId).maybeSingle();if(error)throw error;branding=data||{tenant_id:selectedTenantId};const m={brandPrimary:branding.primary_color||'#163A4D',brandSecondary:branding.secondary_color||'#2F7D78',brandAccent:branding.accent_color||'#D97745',brandSurface:branding.surface_color||'#F8FAFA',brandText:branding.text_color||'#263238',brandLoginTitle:branding.login_title||'',brandLoginSubtitle:branding.login_subtitle||''};Object.entries(m).forEach(([id,v])=>$(id).value=v);renderBrandPreview()}
function renderBrandPreview(){const t=currentTenant();const p=$('brandPrimary').value,s=$('brandSecondary').value;$('previewCompanyName').textContent=t?.name||'RRN Manager';$('previewTitle').textContent=$('brandLoginTitle').value||'Controle patrimonial com mais organização e eficiência';$('previewSubtitle').textContent=$('brandLoginSubtitle').value||'Gerencie equipamentos, responsáveis, setores e movimentações com praticidade e visão centralizada.';$('previewLogo').src=branding?.logo_url||'/img/icon-png.png';const v=$('brandPreview');v.style.backgroundImage=branding?.login_background_url?`linear-gradient(145deg,${p}e6,${s}b8),url('${branding.login_background_url}')`:`linear-gradient(145deg,${p},${s})`}
['brandPrimary','brandSecondary','brandAccent','brandSurface','brandText','brandLoginTitle','brandLoginSubtitle'].forEach(id=>$(id).addEventListener('input',renderBrandPreview));
async function uploadBrand(file,kind){if(!file)return null;const ext=(file.name.split('.').pop()||'webp').toLowerCase();const path=`${selectedTenantId}/${kind}.${ext}`;const {error}=await client.storage.from('tenant-branding').upload(path,file,{upsert:true,cacheControl:'3600',contentType:file.type});if(error)throw error;return client.storage.from('tenant-branding').getPublicUrl(path).data.publicUrl+`?v=${Date.now()}`}
$('saveBrandingButton').onclick=async()=>{try{const logo=await uploadBrand($('brandLogoFile').files[0],'logo');const bg=await uploadBrand($('brandBackgroundFile').files[0],'login-background');const payload={tenant_id:selectedTenantId,primary_color:$('brandPrimary').value,secondary_color:$('brandSecondary').value,accent_color:$('brandAccent').value,surface_color:$('brandSurface').value,text_color:$('brandText').value,login_title:$('brandLoginTitle').value.trim()||null,login_subtitle:$('brandLoginSubtitle').value.trim()||null,updated_by:me.user_id,updated_at:new Date().toISOString()};if(logo)payload.logo_url=logo;if(bg)payload.login_background_url=bg;const {error}=await client.from('tenant_branding').upsert(payload,{onConflict:'tenant_id'});if(error)throw error;toast('Identidade visual salva.');await loadBranding()}catch(e){toast(e.message||'Falha ao salvar identidade.')}};
function renderCompanies(){if(!isPlatformAdmin)return;const counts=Object.fromEntries(tenants.map(t=>[t.id,0]));members.forEach(()=>{});$('companiesBody').innerHTML=tenants.map(t=>`<tr><td class="user-cell"><strong>${esc(t.name)}</strong><small>${esc(t.slug)}</small></td><td><span class="badge badge-${t.status}">${t.status==='active'?'Ativa':'Inativa'}</span></td><td>${t.id===selectedTenantId?members.length:'—'}</td><td>${dateLabel(t.created_at)}</td><td class="align-right"><button class="action-btn" data-select-tenant="${t.id}">Administrar</button></td></tr>`).join('');document.querySelectorAll('[data-select-tenant]').forEach(b=>b.onclick=async()=>{selectedTenantId=b.dataset.selectTenant;renderTenantContext();await loadTenantData();switchView('overview')})}
$('saveCompanyButton').onclick=async()=>{if(!isPlatformAdmin)return toast('Apenas administrador da plataforma.');const {error}=await client.from('tenants').update({name:$('companyName').value.trim(),status:$('companyStatus').value}).eq('id',selectedTenantId);if(error)return toast(error.message);toast('Empresa atualizada.');await loadTenants()};$('openLoginButton').onclick=()=>{const t=currentTenant();if(t)window.open(`${location.origin}/index.html?org=${encodeURIComponent(t.slug)}`,'_blank')};
function updateKpis(){$('kpiUsers').textContent=members.length;$('kpiInvites').textContent=invites.filter(i=>!i.used_at&&new Date(i.expires_at)>new Date()).length}
(async()=>{try{if(!client)throw new Error('Supabase não configurado.');const {data:{session}}=await client.auth.getSession();if(!session?.user)return location.replace('index.html');me=await getMe(session.user.id);if(me.status!=='active'||me.role!=='admin')return location.replace('dashboard.html');isPlatformAdmin=await checkPlatform();$('currentAdmin').textContent=me.name||me.email;$('adminLevel').textContent=isPlatformAdmin?'Administrador da plataforma':'Administrador da empresa';$('adminScopeLabel').textContent=isPlatformAdmin?'Administração da plataforma':'Administração da empresa';$('pageTitle').textContent=isPlatformAdmin?'Central da plataforma':'Administração da empresa';if(!isPlatformAdmin)$('companiesNav').remove();await loadTenants()}catch(e){console.error(e);showNotice(e.message||'Falha ao carregar administração.')}})();
})();